spring:
  application:
    name: config-client #配置中心的配置文件名必须为(如果取dev版本，名字是约定的)config-client-dev.yml
server:
  port: 8881

eureka:
  client:
    service-url:
      #在配置文件中注明自己的服务注册中心的地址,多个时可以逗号分隔http://master:7998/eureka/,http://backup:7999/eureka/
      defaultZone: http://127.0.0.1:8761/eureka/ #为了减少和均匀EurekaServer压力和访问便利，我们对于每个微服务的不同实例，配置Eureka集群都要写的顺序不一样，和自己网段一样的写的靠前
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
feign:
  hystrix:
    enabled: true #Feign是自带断路器的，在低版本的Spring Cloud中，它没有默认打开。需要在配置文件中配置打开它
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

