spring:
  application:
    name: service-hi #spring.application.name,这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name
  #链路追踪
  sleuth:
    web:
      client:
        enabled: true #开启sleuth功能
    sampler:
      probability: 1.0 # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1，即10%概率收集链路数据
  zipkin:
    base-url: http://localhost:9411/ # 指定了 Zipkin 服务器的地址

server:
  port: 8762
eureka:
  client:
    service-url:
      #在配置文件中注明自己的服务注册中心的地址,多个时可以逗号分隔http://master:7998/eureka/,http://backup:7999/eureka/
      defaultZone: http://127.0.0.1:8761/eureka/ #为了减少和均匀EurekaServer压力和访问便利，我们对于每个微服务的不同实例，配置Eureka集群都要写的顺序不一样，和自己网段一样的写的靠前
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}
    prefer-ip-address: true